[mypy]
python_version = 3.11
disallow_untyped_defs = False
warn_return_any = False
warn_unused_ignores = False
ignore_missing_imports = True
explicit_package_bases = True
mypy_path = .
disable_error_code = valid-type,misc

[mypy.fastapi.*]
ignore_missing_imports = True

[mypy.sqlalchemy.*]
ignore_missing_imports = True

[mypy.pydantic.*]
ignore_missing_imports = True

[mypy-database.py]
ignore_errors = True

[mypy-crud.py]
ignore_errors = True
